<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenCoreBuilder.Core\OpenCoreBuilder.Core.csproj" />
    <ProjectReference Include="..\OpenCoreBuilder.Application\OpenCoreBuilder.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
